version: "3.7"

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: goa_php
    restart: "always"
    networks:
      - goa
    volumes:
      - .:/repo:cached
    expose:
      - 9100

  redis:
    image: redis
    container_name: goa_redis
    restart: "always"
    networks:
      - goa

  readis:
    image: hollodotme/readis
    container_name: goa_readis
    restart: "on-failure"
    networks:
      - goa
    volumes:
      - .docker/readis:/code/config:ro
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: goa_nginx
    restart: "always"
    networks:
      - goa
    ports:
      - 80:80
    volumes:
      - .:/repo:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  goa: