<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>GitHub Org Analyzer</title>
	<style>
		/* Sticky footer styles
-------------------------------------------------- */
		html {
			position: relative;
			min-height: 100%;
		}

		body {
			/* Margin bottom by footer height */
			margin-bottom: 60px;
		}

		.footer {
			position: absolute;
			bottom: 0;
			width: 100%;
			/* Set the fixed height of the footer here */
			height: 60px;
			line-height: 60px; /* Vertically center the text there */
			background-color: #f5f5f5;
		}

		main {
			position: absolute;
			bottom: 70px;
			top: 70px;
		}

		#description {
			position: absolute;
			left: 15px;
			top: 0;
			bottom: 0;
			right: 51%;
			background-color: #f8f9fa;
			border-radius: 5px;
			padding: 15px;
		}

		#eventSourceOutput {
			position: absolute;
			left: 51%;
			right: 15px;
			bottom: 0;
			top: 0;

			/* Set the fixed height of the footer here */
			background-color: #0c0c0c;
			border-radius: 5px;
			color: #ffffff;
			padding: 15px;
			overflow-y: auto;
			overflow-x: auto;
			font-size: small;
			font-family: "Courier New", monospace;
		}

		/* Custom page CSS
		-------------------------------------------------- */
		/* Not required for template or sticky footer method. */

		body > .container {
			padding: 60px 15px 0;
		}

		.footer > .container {
			padding-right: 15px;
			padding-left: 15px;
		}

		code {
			font-size: 80%;
		}

		.highcharts-tooltip h3 {
			margin: 0.3em 0;
		}

		.modal-lg {
			min-width: 80%;
		}
	</style>
</head>
<body>
<header>
	<!-- Fixed navbar -->
	<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light" style="max-height: 50px;">
		<a class="navbar-brand" href="#">
			<img src="img/github-icon.png" class="img-fluid" style="max-height: 45px;" alt="GitHub">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
				aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
				</li>
			</ul>
		</div>
	</nav>
</header>

<main role="main" class="container-fluid">
	<div id="description">
		<h1>GitHub Organization Analyzer</h1>
		<p>
			Enter your personal access token, which you can
			<a href="https://github.com/settings/tokens/new" target="_blank">obtain here</a>,
			the GitHub organization name and hit "ANALYZE".
		</p>
		<p>
			<b>Please note:</b>
		</p>
		<ul>
			<li>
				You can analyze any organization and their public repositories like e.g.
				<a href="https://github.com/php" target="_blank">github.com/php</a>.
			</li>
			<li>
				If you want to analyze an organization incl. their private repositories,
				your GitHub user needs to have access to this organization.
			</li>
			<li>
				Even though this application will not store your personal access token,
				you should revoke it once you're done with the analysis.
			</li>
		</ul>

		<hr>

		<form id="analyzeForm" data-eventsource-url="/eventSource.php">
			<div class="form-group">
				<label for="personalAccessToken">Personal access token</label>
				<input type="text" name="personalAccessToken" class="form-control" id="personalAccessToken"
					   placeholder="Enter personal access token">
				<small id="tokenHelp" class="form-text text-muted">
					The personal access token is needed to authenticate at the
					<a href="https://developer.github.com/v4/" target="_blank">GitHub GraphQL API</a>.
				</small>
			</div>
			<div class="form-group">
				<label for="organizationName">GitHub organization name</label>
				<input type="text" name="organizationName" class="form-control" id="organizationName"
					   placeholder="Enter organization name">
			</div>
			<div class="row">
				<div class="col">
					<button type="submit" class="btn btn-primary" id="analyzeBtn">ANALYZE</button>
				</div>
				<div class="col text-right">
					<button type="button" class="btn btn-danger" id="stopBtn" disabled>STOP</button>
				</div>
			</div>
		</form>

		<div class="text-center" id="waitImage" style="display: none;">
			<img src="img/octocat-calculating.gif" class="img-fluid" alt="octocat calculating"
				 style="max-height: 200px;">
		</div>

	</div>
	<div id="eventSourceOutput">

	</div>
</main>

<!-- Modal -->
<div class="modal fade" id="chartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	 aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="chartModalLabel">Charts</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div id="bubbleChart" style="height: 600px; width: 100%; margin: 0 auto"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<footer class="footer">
	<div class="container text-center">
		<span class="text-muted">
			This website is crafted with ❤️and
			<a href="https://php.net" target="_blank">PHP</a> as an open source project. You can
			<a href="https://github.com/hollodotme/github-org-analyzer" target="_blank">contribute on GitHub</a>.
		</span>
	</div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="/js/main.js"></script>
</body>
</html>