<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/main.css">
	<meta name="description" content="Online analyzer for GitHub organizations using the GraphQL API">
	<meta name="keywords" content="GitHub, Organization, Analyzer, GraphQL, FastCGI Client, PHP, OSS">
	<meta name="HandheldFriendly" content="True"/>
	<meta name="geo.region" content="DE-SN"/>
	<meta name="geo.placename" content="Dresden"/>
	<meta name="geo.position" content="51.052088;13.741672"/>
	<meta name="ICBM" content="51.052088, 13.741672"/>
	<meta name="twitter:site" content="@hollodotme">
	<meta name="twitter:creator" content="@hollodotme">
	<script type="application/ld+json">
		{
			"@context": "http://schema.org",
			"@type": "Person",
			"name": "GitHub Organization Analyzer",
			"image": "https://analyze-github.org/img/chart.png",
			"url": "https://analyze-github.org"
		}
	</script>
	<meta property="article:author" content="https://github.com/hollodotme"/>
	<meta property="article:publisher" content="https://github.com/hollodotme"/>

	<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192" href="/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
	<link rel="manifest" href="/favicon/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">

	<link rel="canonical" href="https://analyze-github.org"/>
	<meta name="referrer" content="origin"/>

	<meta property="og:site_name" content="GitHub Organization Analyzer"/>
	<meta property="og:type" content="article"/>
	<meta property="og:title" content="Home | GitHub Organization Analyzer"/>
	<meta property="og:description" content="Online analyzer for GitHub organizations using the GraphQL API"/>
	<meta property="og:url" content="https://analyze-github.org"/>
	<meta property="og:image" content="https://analyze-github.org/img/chart.png"/>
	<meta property="article:published_time" content="<?= date( 'c' ) ?>"/>
	<meta property="article:modified_time" content="<?= date( 'c' ) ?>"/>
	<meta property="article:tag" content="GitHub"/>
	<meta property="article:tag" content="Organization"/>
	<meta property="article:tag" content="Analyzer"/>
	<meta property="article:tag" content="PHP"/>
	<meta property="article:tag" content="GraphQL"/>
	<meta property="article:tag" content="OSS"/>
	<meta name="twitter:card" content="summary_large_image"/>
	<meta name="twitter:title" content="Home | GitHub Organization Analyzer"/>
	<meta name="twitter:description" content="Online analyzer for GitHub organizations using the GraphQL API"/>
	<meta name="twitter:url" content="https://analyze-github.org"/>
	<meta name="twitter:image:src" content="https://analyze-github.org/img/chart.png"/>
	<meta name="generator" content="Handmade with ❤️"/>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<title>GitHub Org Analyzer</title>
</head>
<body>
<header>
	<!-- Fixed navbar -->
	<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light" style="max-height: 50px;">
		<a class="navbar-brand" href="/">
			<img src="img/github-icon.png" class="img-fluid" style="max-height: 45px;" alt="GitHub">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
				aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
				</li>
			</ul>
		</div>
	</nav>
</header>

<main role="main" class="container-fluid">
	<div id="description">
		<h1>GitHub Organization Analyzer</h1>
		<p>
			Enter your personal access token, which you can
			<a href="https://github.com/settings/tokens/new" target="_blank">obtain here</a>,
			the GitHub organization name and hit "ANALYZE". As a result a modal opens showing you a bubble chart
			for the github organization.
		</p>
		<p>
			<b>Please note:</b>
		</p>
		<ul>
			<li>
				Your personal access token must have at least the <code>repo:public_repo</code> scope to analyze
				public repositories. In Order to also analyze private repositories you must select the whole
				<code>repo</code> scope.
			</li>
			<li>
				You can analyze any organization and their public repositories like e.g.
				<a href="https://github.com/php" target="_blank">github.com/php</a>.
			</li>
			<li>
				If you want to analyze an organization incl. their private repositories,
				your GitHub user needs to have access to this organization.
			</li>
			<li>
				Even though this application will not store your personal access token,
				you should revoke it once you're done with the analysis.
			</li>
		</ul>

		<hr>

		<form id="analyzeForm" data-eventsource-url="/eventSource.php">
			<div class="form-group">
				<label for="personalAccessToken">Personal access token</label>
				<input type="text" name="personalAccessToken" class="form-control" id="personalAccessToken"
					   placeholder="Enter personal access token">
				<small id="tokenHelp" class="form-text text-muted">
					The personal access token is needed to authenticate at the
					<a href="https://developer.github.com/v4/" target="_blank">GitHub GraphQL API</a>.
				</small>
			</div>
			<div class="form-group">
				<label for="organizationName">GitHub organization name</label>
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text">github.com/</span>
					</div>
					<input type="text" name="organizationName" class="form-control" id="organizationName"
						   placeholder="Enter organization name">
				</div>
			</div>
			<div class="row align-items-center">
				<div class="col-2">
					<button type="submit" class="btn btn-primary" id="analyzeBtn">ANALYZE</button>
				</div>
				<div class="col">
					<div class="form-check form-check-inline">
						<input class="form-check-input" type="checkbox" id="useCommitDate" name="useCommitDate"
							   value="On">
						<label class="form-check-label" for="useCommitDate">Commit-based analysis</label>
						&nbsp;
						<small class="form-text text-muted">(Way slower, but more accurate.)</small>
					</div>
				</div>
				<div class="col-2 text-right">
					<button type="button" class="btn btn-danger" id="stopBtn" disabled>STOP</button>
				</div>
			</div>
		</form>

		<div class="text-center" id="waitImage" style="display: none;">
			<img src="img/octocat-calculating.gif" class="img-fluid" alt="octocat calculating"
				 style="max-height: 200px;">
		</div>

	</div>
	<div id="eventSourceOutput">

	</div>
</main>

<!-- Modal -->
<div class="modal fade" id="chartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	 aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="chartModalLabel">Charts</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div id="bubbleChart" style="height: 600px; width: 100%; margin: 0 auto"></div>
				<div class="small text-muted text-center">
					You can zoom into a date range by dragging an area on the chart.
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<footer class="footer">
	<div class="container text-center">
		<span class="text-muted">
			This website is crafted with ❤️and
			<a href="https://php.net" target="_blank">PHP</a> as an open source project. You can
			<a href="https://github.com/hollodotme/analyze-github.org" target="_blank">contribute on GitHub</a>.
		</span>
	</div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="/js/main.js"></script>
</body>
</html>